### ISSUE TITLE
Hey can i port this to fabric.

### ISSUE THREAD

**Issue by SonicFangame** [Majed6/minehaptics#1]
i am planning to port this to fabric but i want to upload the port to modrinth of course i will mention it's you're mod but can i.

**Comment by Majed6** [comment]
It would be an honor! Yes please do. I'm planning on publishing on modrinth as well. Are you going to create a PR or a dedicated repository? I'm ok with both btw but it would be a bit confusing to have them both under different names. Again do whatever you feels is best. The more compatibility the community has the better for the community.

**Comment by Majed6** [comment]
modrinth publication will start after I'm done with the process in curseforge.

**Comment by SonicFangame** [comment]
great! i may not be able to do the port. but if i can what license do i use? also for the modrinth team to accept my port you may have to keep this open.

**Comment by awesomedudeer** [comment]
also i huge inspiration to port this to fabric is questcraft.

**Comment by Majed6** [comment]
You can do it! The mod is quite simple. All you need is to replicate this commit https://github.com/Majed6/minehaptics/commit/850dd0400ef1e6d16528c54a0e258a8eb1d5f114  in whatever mod loader you're going to use.  This file more specifically MyForgeEventHandler.java .

I had no knowledge of minecraft modding and limited understanding of java development lifecycle and here I am. Just start and see how far you can go!.


As for the license, I haven't decided yet. Especially that this is my first mod. I usually go with MIT thought.


Also, are you sure this issue has to be open? Can't it be closed?

One last thing. if you're going to create a dedicated repo for the port, please don't use the name minehaptics just in case someone want to create a PR for fabric in this repo. Having two different mods would be less confusing for the community than having the same mod published twice under similar names IMO. Best thing is to have one mod but I understand how complicated that would be.

**Comment by SonicFangame** [comment]
Question what use is the MineHaptic.java and Utils.java files? sorry for the late response.

**Comment by SonicFangame** [comment]
also if they are important could you say what they do and why.

**Comment by Majed6** [comment]
MineHaptics registers the MyForgeEventHandler in the event bus. You can ignore it if the mod loader doesn't require registeration somehow. 

Utils is the 2nd important file it contains utilities that help facilitates features that are not supported by the mod loader directly. Like loading .tact files into a string variable and isSnowingOnPlayer which doesn't exist as far as I know on forge. This class should mostly be portable across different mod loaders  🤞 .

PS: Feel free to link up on discord as issues are not quite suited for chatting. Either case feel free to continue using this issue. I would more than happy to assist you in porting this.

PPS: I have to go offline now and I'll get back to you as soon as possible in the next 48 hours.

**Comment by SonicFangame** [comment]
You have a discord?

**Comment by Majed6** [comment]
Yes, my username should be in your email box for the notification of this message.

**Comment by SonicFangame** [comment]
could you send a link

**Comment by Majed6** [comment]
Not a server. I meant a user chat. What's your handler? I can DM you first if you want.

**Comment by SonicFangame** [comment]
you mean username

**Comment by Majed6** [comment]
yup

**Comment by Majed6** [comment]
A port has been implemented by bhaptics team here https://www.curseforge.com/minecraft/mc-mods/hapticcraft
